baseURL = "https://www.ai-tan.jp/"
languageCode = "ja"
title = "ã‚ã„ãŸã‚“ï¼AI Ã— è‹±å˜èª = åˆæ ¼ğŸŒ¸"
pluralizeListTitles = false

[pagination]
  pagerSize = 100
  path = "page"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML", "JSON"]
section = ["HTML", "JSON"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]
